name: Nightly iceoryx run

on:
  schedule:
  - cron: "0 6 * * 1-5"
  workflow_dispatch:

jobs:
  build-test-macos:
    runs-on: macos-latest
    # prevent stuck jobs consuming macos runners for 6 hours
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - run: ./tools/ci/build-test-macos.sh

  clang-tidy-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install iceoryx dependencies and clang-tidy
        uses: ./.github/actions/install-iceoryx-deps-and-clang
      - name: clang-tidy full scan of all entries in .clang-tidy-diff-scans.txt
        run: |
          ./tools/scripts/clang_tidy_check.sh scan_list .clang-tidy-diff-scans.txt


